# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

from azure.cli.testsdk import ResourceGroupPreparer
from azure.cli.testsdk.scenario_tests import AllowLargeResponse
from .test_aks_commands import AzureKubernetesServiceScenarioTest


class AksSafeguardsScenario(AzureKubernetesServiceScenarioTest):
    # TODO: add tests here
    @AllowLargeResponse(size_kb=9999)
    @ResourceGroupPreparer(name_prefix='cli-', random_name_length=8, location="westus2")
    def test_aks_deployment_safeguards(self):
        self.kwargs.update({
            'aks_name': self.create_random_name(prefix='akssafeguards-', length=20),
            'ssh_key_value': self.generate_ssh_keys(),
            'vm_size': 'standard_a8_v2'
        })

        # Create AKS cluster
        aks_cluster = self.cmd('aks create -g {rg} -n {aks_name} --ssh-key-value={ssh_key_value} --node-vm-size {vm_size} --enable-addons azure-policy', checks=[
            self.check('name', '{aks_name}'),
            self.check('agentPoolProfiles[0].vmSize', '{vm_size}'),
        ]).get_output_in_json()

        # Enable safeguards with PSS level using -c/-g syntax
        self.cmd('aks safeguards create -c {aks_name} -g {rg} --level Warn --pss-level Baseline', checks=[
            self.check('properties.level', 'Warn'),
            self.check('properties.podSecurityStandardsLevel', 'Baseline'),
        ])

        # Get Safeguards using -c/-g syntax
        self.cmd('aks safeguards show -c {aks_name} -g {rg}', checks=[
            self.check('properties.level', 'Warn'),
            self.check('properties.podSecurityStandardsLevel', 'Baseline'),
            self.check('properties.excludedNamespaces', None),
        ])

        self.cmd('aks safeguards list -c {aks_name} -g {rg}', checks=[
            self.check('length(@)', 1),
            self.check('[0].properties.level', 'Warn'),
            self.check('[0].properties.podSecurityStandardsLevel', 'Baseline'),
            self.check('[0].properties.excludedNamespaces', None),
        ])

        # Change excluded namespaces and PSS level
        self.cmd('aks safeguards update -c {aks_name} -g {rg} --excluded-namespaces ns1 --pss-level Restricted', checks=[
            self.check('properties.excludedNamespaces[0]', 'ns1'),
            self.check('properties.podSecurityStandardsLevel', 'Restricted'),
        ])

        # Disable Safeguards using -c/-g syntax
        self.cmd('aks safeguards delete -c {aks_name} -g {rg} --yes')

        # delete the aks cluster
        self.cmd('aks delete -g {rg} -n {aks_name} --yes --no-wait')
